# Generated by Django 3.1.1 on 2020-10-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sport",
            name="name",
            field=models.CharField(max_length=40),
        ),
    ]
