default_language_version:
  python: python3.7
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-merge-conflict
  - repo: https://github.com/PyCQA/isort
    rev: 5.5.4
    hooks:
      - id: isort
        name: isort - Sort imports
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        exclude: migrations/
        name: black - Automatically format code
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        exclude: migrations/
        name: flake8 - Lint [PEP8] for manual review
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        name: bandit - Finds common security issues in Python
        args: ['-iii', '-ll']