  version: '3'

  services:
    postgres:
      container_name: nsi_db
      restart: always
      image: postgres:12
      ports:
        - "5432:5432"
      env_file:
        - app/.env
      volumes:
      - postgres_data:/var/lib/postgresql/data
      networks:
        - postgres_network

    web:
      container_name: nsi_backend
      volumes:
      - .:/app
      env_file:
        - app/.env
      build:
        context: .
        dockerfile: config/django/Dockerfile
      depends_on:
        - postgres
      networks:
        - postgres_network
        - nginx_network

    nginx:
      image: nginx:1.13
      build:
        context: ./config/nginx
        dockerfile: Dockerfile
      ports:
      - 80:80
      volumes:
      - ./config/nginx/conf.d:/nginx.conf
      - static_volume:/app/static
      - media_volume:/app/media
      depends_on:
      - web
      networks:
      - nginx_network
  networks:
    postgres_network:
      driver: bridge
    nginx_network:
      driver: bridge
  volumes:
    postgres_data:
    static_volume:
    media_volume: