  version: '3'

  services:
    postgres:
      container_name: nsi_db
      restart: always
      image: postgres:12
      ports:
        - "5432:5432"
      env_file:
        - app/.env
      volumes:
      - postgres_data:/var/lib/postgresql/data
      networks:
        - postgres_network
    elasticsearch:
      image: elasticsearch
      build:
        context: .
        dockerfile: config/elasticsearch/Dockerfile
      environment:
        - xpack.security.enabled=false
        - discovery.type=single-node
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
      cap_add:
        - IPC_LOCK
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
      networks:
        - elastic_network
      ports:
        - 9200:9200
    web:
      container_name: nsi_backend
      volumes:
      - .:/app
      - static_volume:/staticfiles
      - media_volume:/mediafiles
      env_file:
        - app/.env
      build:
        context: .
        dockerfile: config/django/Dockerfile
      depends_on:
        - postgres
        - elasticsearch
      expose:
        - 8000
      networks:
        - postgres_network
        - nginx_network
        - elastic_network

    nginx:
      image: nginx:latest
      build:
        context: ./config/nginx
        dockerfile: Dockerfile
      ports:
      - 8000:80
      volumes:
      - ./config/nginx/conf.d:/nginx.conf
      - static_volume:/staticfiles
      - media_volume:/mediafiles
      depends_on:
      - web
      networks:
      - nginx_network
  networks:
    postgres_network:
      driver: bridge
    nginx_network:
      driver: bridge
    elastic_network:
      driver: bridge
  volumes:
    postgres_data:
    static_volume:
    media_volume:
    elasticsearch-data:
      driver: local