  version: '3'

  services:
    postgres:
      container_name: nsi_db
      restart: always
      image: postgres:12
      ports:
        - "5432:5432"
      env_file:
        - app/.env
      volumes:
      - postgres_data:/var/lib/postgresql/data
      networks:
        - postgres_network
    web:
      container_name: nsi_backend
      command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      volumes:
      - .:/app
      env_file:
        - app/.env
      build:
        context: .
        dockerfile: config/django/Dockerfile
      ports:
        - "8000:8000"
      depends_on:
        - postgres
      networks:
        - postgres_network
  networks:
    postgres_network:
      driver: bridge
  volumes:
    postgres_data: