# Generated by Django 3.1.1 on 2020-09-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('region', models.CharField(max_length=63)),
            ],
            options={
                'ordering': ['region'],
            },
        ),
    ]
