# Generated by Django 3.1.1 on 2020-09-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.CharField(choices=[('nord', 'Nord-Norge'), ('midt', 'Midt-Norge'), ('vest', 'Vestlandet'), ('sør', 'Sørlandet'), ('øst', 'Østlandet')], max_length=4),
        ),
    ]
