# Generated by Django 3.1.2 on 2020-10-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0002_auto_20201005_2318"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="region",
            field=models.CharField(
                choices=[
                    ("nord", "Nord-Norge"),
                    ("midt", "Midt-Norge"),
                    ("vest", "Vestlandet"),
                    ("sor", "Sørlandet"),
                    ("ost", "Østlandet"),
                ],
                max_length=4,
            ),
        ),
    ]
