##################### ElasticSearch Configuration #####################

################################## Discovery ##################################

discovery.type: "single-node"

############################## Network And HTTP ###############################

network.host: 0.0.0.0