# Generated by Django 3.1.1 on 2020-09-23 08:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
        ('groups', '0001_initial'),
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('description', models.CharField(max_length=1023, null=True)),
                ('cost', models.CharField(max_length=511, null=True)),
                ('equipment', models.CharField(max_length=511, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('MX', 'Mix'), ('A', 'Any')], default='A', max_length=2)),
                ('skill_level', models.CharField(choices=[('NONE', 'No expectations'), ('LOW', 'Low'), ('MED', 'Medium'), ('HI', 'High'), ('PRO', 'Professional')], default='NONE', max_length=4)),
                ('season', models.CharField(max_length=511, null=True)),
                ('facebook_link', models.CharField(max_length=127, null=True)),
                ('instagram_link', models.CharField(max_length=127, null=True)),
                ('webpage', models.CharField(max_length=127, null=True)),
                ('availability', models.CharField(choices=[('OP', 'Open'), ('CL', 'Closed'), ('FU', 'Full'), ('TO', 'Tryouts')], default='FU', max_length=2)),
                ('image', models.ImageField(null=True, upload_to='teams')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.city')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='TryoutDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('team', models.ManyToManyField(related_name='tryout_dates', to='teams.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('team', models.ManyToManyField(related_name='schedule', to='teams.Team')),
            ],
        ),
    ]
