# Generated by Django 3.1.1 on 2020-09-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('full_capacity', models.BooleanField()),
                ('tryouts', models.BooleanField()),
                ('registration_open', models.BooleanField()),
                ('club_sport', models.IntegerField()),
            ],
        ),
    ]
