# Generated by Django 3.1.2 on 2020-10-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="description",
        ),
        migrations.AddField(
            model_name="team",
            name="long_description",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="short_description",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
