# Generated by Django 3.1.1 on 2020-09-18 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='team',
            field=models.ManyToManyField(null=True, to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='tryoutdates',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
