# Generated by Django 3.1.1 on 2020-09-18 12:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 12, 26, 18, 173460, tzinfo=utc)),
        ),
    ]
