# Generated by Django 3.1.1 on 2020-09-10 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubSports', '0003_auto_20200910_2256'),
        ('teams', '0002_auto_20200909_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='club_sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubSports.clubsport'),
        ),
    ]
