# Generated by Django 3.1.2 on 2020-10-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20201007_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook_link',
            field=models.URLField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram_link',
            field=models.URLField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='webpage',
            field=models.URLField(max_length=127, null=True),
        ),
    ]
