# Generated by Django 3.1.1 on 2020-09-18 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20200918_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
