# Generated by Django 3.1.1 on 2020-09-18 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20200918_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='TryoutDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('team', models.ManyToManyField(to='teams.Team')),
            ],
        ),
    ]
