# Generated by Django 3.1.1 on 2020-09-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20200918_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='team',
        ),
        migrations.RemoveField(
            model_name='tryoutdates',
            name='team',
        ),
    ]
