# Generated by Django 3.1.1 on 2020-09-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_tryoutdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='team',
            field=models.ManyToManyField(related_name='schedule', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='tryoutdates',
            name='team',
            field=models.ManyToManyField(related_name='tryout_dates', to='teams.Team'),
        ),
    ]
