  version: '3'

  services:
    postgres:
      image: postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=nsi
        - POSTGRES_USER=django
        - POSTGRES_PASSWORD=django
        - POSTGRES_HOST_AUTH_METHOD=trust
      networks:
        - postgres_network
    migrate:
      build: .
      command: python manage.py migrate
      networks:
        - postgres_network
      depends_on:
        - postgres
    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - postgres
        - migrate
  networks:
    postgres_network:  # <-- add the bridge
      driver: bridge