  version: '3'

  services:
    postgres:
      image: postgres
      ports:
        - "5432:5432"
      networks:
        - postgres_network
    migrate:
      build: .
      command: python manage.py migrate
      networks:
        - postgres_network
      depends_on:
        - postgres
    web:
      build:
        context: .
        dockerfile: Dockerfile
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      networks:
        - postgres_network
      depends_on:
        - postgres
        - migrate
  networks:
    postgres_network:  # <-- add the bridge
      driver: bridge