[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
default_section = "THIRDPARTY"
known_first_party = ['app', 'cities', 'clubs', 'groups', 'interest', 'sports', 'teams']
known_django = ['django']
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
forced_separate = [
    "django.contrib",
    "django.util"
    ]
skip = [
    "__init__.py",
    "migrations",
    "venv"
    ]