[tool.black]
line-length = 88
include = '\.pyi?$'

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
default_section = "THIRDPARTY"
known_first_party = ['app', 'cities', 'clubs', 'groups', 'interest', 'sports', 'teams']
known_django = ['django']
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
forced_separate = [
    "django.contrib",
    "django.util"
    ]
skip = [
    "__init__.py",
    "migrations"
    ]


[tool.coverage]
[tool.coverage.run]
# whether to measure branch coverage in addition to statement coverage. The result only included in HTML and JSON reports
branch = true

# files to omit from coverage
omit = [
    "*/__init__.py",
    "*/apps.py",
    "*/migrations/*",
    "*/settings/*",
    "*/urls.py",
    "*wsgi.py",
    "manage.py",
    "*/tests.py",
    "*/venv/*"
]

[tool.coverage.report]
# Exclude lines matching one of the RegEx-expressions in the list.
exclude_lines = []

# Show missing lines in the report
show_missing = true

# Exclude empty files from the report
skip_empty = true

# Sort the text report. Allowed values are “Name”, “Stmts”, “Miss”, “Branch”, “BrPart”, or “Cover”.
sort = "Name"


[tool.coverage.html]
# where to store the html report
directory = "coverage_report"