# Generated by Django 3.1.1 on 2020-09-09 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sportsklubb', max_length=30)),
                ('description', models.TextField()),
                ('coverPhoto', models.ImageField(upload_to='clubSports')),
                ('contactPerson', models.CharField(blank=True, default='', max_length=30)),
                ('contactEMail', models.EmailField(max_length=254)),
                ('sportType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.sport')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
