# Generated by Django 3.1.1 on 2020-09-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubSports', '0002_auto_20200909_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubsport',
            name='contactEMail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clubsport',
            name='contactPerson',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clubsport',
            name='coverPhoto',
            field=models.ImageField(null=True, upload_to='clubSports'),
        ),
    ]
