# Generated by Django 3.1.1 on 2020-09-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20200909_1509'),
        ('clubSports', '0002_auto_20200909_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsport',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clubsport',
            name='contactEMail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clubsport',
            name='contactPerson',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clubsport',
            name='coverPhoto',
            field=models.ImageField(null=True, upload_to='clubSports'),
        ),
    ]
