# Generated by Django 3.1.1 on 2020-09-10 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubSports', '0003_auto_20200910_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubsport',
            old_name='contactEMail',
            new_name='contactMail',
        ),
    ]
