# Generated by Django 3.1.1 on 2020-09-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubSports', '0003_auto_20200910_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubsport',
            old_name='contactEMail',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='clubsport',
            old_name='contactPerson',
            new_name='contact_person',
        ),
        migrations.RenameField(
            model_name='clubsport',
            old_name='coverPhoto',
            new_name='cover_photo',
        ),
        migrations.RenameField(
            model_name='clubsport',
            old_name='sportType',
            new_name='sport_type',
        ),
    ]
