# Generated by Django 3.1.1 on 2020-10-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('left', models.CharField(max_length=20)),
                ('right', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
    ]
