# Generated by Django 3.1.1 on 2020-10-19 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_auto_20201005_2318'),
        ('questionnaire', '0004_auto_20201019_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Question_alternative', to='questionnaire.question')),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Question_answer', to='questionnaire.question'),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=25)),
                ('alternatives', models.ManyToManyField(related_name='alternative', to='questionnaire.Alternative')),
                ('sports', models.ManyToManyField(related_name='Sports', to='sports.Sport')),
            ],
        ),
    ]
