# Generated by Django 3.1.1 on 2020-10-02 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_key', models.CharField(max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
            options={
                'ordering': ['group'],
            },
        ),
        migrations.AddConstraint(
            model_name='interest',
            constraint=models.UniqueConstraint(fields=('cookie_key', 'group'), name='unique_interest'),
        ),
    ]
