# Generated by Django 3.1.1 on 2020-10-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='cookie_key',
            field=models.CharField(max_length=100),
        ),
    ]
