# Generated by Django 3.1.1 on 2020-09-21 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='email',
        ),
        migrations.AddField(
            model_name='interest',
            name='cookie_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='interest',
            constraint=models.UniqueConstraint(fields=('cookie_key', 'group'), name='unique_interest'),
        ),
    ]
