# Generated by Django 3.1.1 on 2020-09-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['sport']},
        ),
        migrations.AddField(
            model_name='interest',
            name='club',
            field=models.CharField(default='test', max_length=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
