# Generated by Django 3.1.2 on 2020-11-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='interest',
            name='unique_interest',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='cookie_key',
            new_name='session_id',
        ),
        migrations.AddConstraint(
            model_name='interest',
            constraint=models.UniqueConstraint(fields=('session_id', 'group'), name='unique_interest'),
        ),
    ]
