# Generated by Django 3.1.1 on 2020-09-09 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20200909_1509'),
        ('interest', '0002_auto_20200908_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.club'),
        ),
    ]
