# Generated by Django 3.1.1 on 2020-09-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='highlighted',
        ),
    ]
