# Generated by Django 3.1.1 on 2020-09-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='how_to_register',
            new_name='register_info',
        ),
    ]
