# Generated by Django 3.1.1 on 2020-10-05 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="club",
            old_name="pricing",
            new_name="membership_fee",
        ),
    ]
