# Generated by Django 3.1.1 on 2020-09-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='contact_email',
            field=models.EmailField(max_length=127, null=True),
        ),
    ]
