# Generated by Django 3.1.1 on 2020-10-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20201005_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
