# Generated by Django 3.1.1 on 2020-09-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_remove_club_highlighted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='owner',
        ),
    ]
