# Generated by Django 3.1.1 on 2020-09-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20200909_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='contact_phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
