# Generated by Django 3.1.1 on 2020-09-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        ('clubs', '0001_initial'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Group', max_length=30)),
                ('description', models.TextField(max_length=500, null=True)),
                ('cover_photo', models.ImageField(null=True, upload_to='groups')),
                ('contact_email', models.EmailField(max_length=254, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='cities.city')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='clubs.club')),
                ('sports', models.ManyToManyField(to='sports.Sport')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
