# Generated by Django 3.1.1 on 2020-09-18 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sportsklubb', max_length=30)),
                ('description', models.TextField(max_length=500, null=True)),
                ('cover_photo', models.ImageField(null=True, upload_to='groups')),
                ('contact_person', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('contact_email', models.EmailField(max_length=254, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('sport_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.sport')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
