# Generated by Django 3.1.1 on 2020-09-17 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('clubs', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='cities.city'),
        ),
        migrations.AlterField(
            model_name='group',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='Group', max_length=30),
        ),
    ]
