# Generated by Django 3.1.1 on 2020-10-05 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0002_auto_20201005_2318"),
        ("cities", "0002_auto_20201005_2318"),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="cities.city",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="club",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="clubs.club",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="contact_email",
            field=models.EmailField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(default="Group", max_length=40),
        ),
    ]
