# Generated by Django 3.1.1 on 2020-09-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
        ('groups', '0002_auto_20200917_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='sport_type',
        ),
        migrations.AddField(
            model_name='group',
            name='sport_type',
            field=models.ManyToManyField(null=True, to='sports.Sport'),
        ),
    ]
