# Generated by Django 3.1.1 on 2020-09-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
        ('groups', '0003_auto_20200918_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='sport_type',
            field=models.ManyToManyField(to='sports.Sport'),
        ),
    ]
