# Generated by Django 3.1.1 on 2020-09-21 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20200920_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='sport_type',
            new_name='sports',
        ),
    ]
