on:
  pull_request:
    branches:
      - dev

name: Backend build, test and push to Azure

jobs:
    build-and-deploy:
        env:
          DJANGO_SECRET_KEY: ${secrets.DJANGO_SECRET_KEY}
          POSTGRES_USER: ${secrets.POSTGRES_USER}
          POSTGRES_PASSWORD: ${secrets.POSTGRES_PASSWORD}
          POSTGRES_DB: ${secrets.POSTGRES_DB}
          IMAGE_VERSION: ${{ github.actor }}

        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build image'
          run: |
            docker-compose -f docker-compose.prod.yml build

        - name: 'Run tests and linting'
          run: |
            docker-compose -f docker-compose.prod.yml up --abort-on-container-exit

        - name: 'Push image to ACR'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker-compose -f docker-compose.prod.yml push

        - uses: azure/appservice-settings@v1
          with:
            app-name: kundestyrt-nsi-dev-backend
            slot-name: ${{ env.IMAGE_VERSION }}
            app-settings-json: '${{ secrets.APP_SETTINGS }}'
            general-settings-json: '{"alwaysOn": "false", "webSocketsEnabled": "true"}'


        - name: Deploy web App using GH Action azure/webapps-deploy
          uses: azure/webapps-deploy@v2
          with:
            app-name: kundestyrt-nsi-dev-backend
            slot-name: ${{ env.IMAGE_VERSION }}
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            images:
            - acrkundestyrtnsi.azurecr.io/studentidrett-backend:${{ env.IMAGE_VERSION }}
            - acrkundestyrtnsi.azurecr.io/studentidrett-backend:nginx-${{ env.IMAGE_VERSION }}

        - name: Azure logout
          run: |
            az logout
