name: Django Tests

# triggers for our workflow
on:
  # opening a pull request to master and develop branch will be a trigger
  pull_request:
    branches:
      - dev
      - main
  # any code pushed to master and develop branch will also be a trigger
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:

    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - name: Checkout Actions
      uses: actions/checkout@v2

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create Docker Image
      run: |
        python -m pip install --upgrade pip
        docker-compose up -d --build

    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: app_web
